apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-image-puller
  namespace: 6e0e49-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: builder
    namespace: 6e0e49-dev
  - kind: ServiceAccount
    name: builder
    namespace: 6e0e49-dev
  - kind: ServiceAccount
    name: builder
    namespace: 6e0e49-test
  - kind: ServiceAccount
    name: builder
    namespace: 6e0e49-prod
