name: Auth API DEV CD

on:
  push:
    branches:
      - development
    paths:
      - "auth-api/**"

env:
  IMAGE_NAME: auth-api
  TAG_NAME: dev

jobs:
  auth-api-dev:
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/sbc-auth'
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          ./scripts/install_tools.sh
          oc version
          op --version
      - name: Log into registry
        run: echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ secrets.OPENSHIFT_REGISTRY }} -u ${{ secrets.OPENSHIFT_SA_NAME}} --password-stdin
      - name: Pull image
        working-directory: ./auth-api
        run: docker pull ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
      - name: Build image
        uses: vrutkovs/action-s2i@master
        with:
          path: ./auth-api
          base: ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
          image: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/${{env.IMAGE_NAME}}
      - name: Push image
        working-directory: ./auth-api
        run: |
          IMAGE_ID=${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/$IMAGE_NAME
          docker push $IMAGE_ID:latest
          docker image tag $IMAGE_ID:latest $IMAGE_ID:$TAG_NAME
          docker push $IMAGE_ID:$TAG_NAME
      - name: Login Openshift
        working-directory: ./auth-api
        run: |
          oc ${{ secrets.oc_parameters }}
      - name: Set Deployment Environement Variables
        working-directory: .
        run: |
          vaults='[{ "vault": "shared", "application": ["keycloak", "jwt"]}, {"vault": "relationship","application": ["postgres-auth", "auth-api", "sentry"]}]'
          ./scripts/1pass.sh ${{ secrets.op_parameters }} -m "secret" -e "${TAG_NAME}" -v "${vaults}" -a "${IMAGE_NAME}-${TAG_NAME}" -n ${{ secrets.OPENSHIFT_REPOSITORY_DEV }}
      - name: Rollout new deployment
        working-directory: ./auth-api
        run: |
          oc rollout latest dc/$IMAGE_NAME-${TAG_NAME} -n ${{ secrets.OPENSHIFT_REPOSITORY_DEV }}
          oc rollout status dc/$IMAGE_NAME-${TAG_NAME} -n ${{ secrets.OPENSHIFT_REPOSITORY_DEV }} -w
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*Auth API Build and Deploy to ${{env.TAG_NAME}}*"
          channel: "#relationship-developers"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  auth-api-postman-test:
    needs: auth-api-dev
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/sbc-auth'
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          ./scripts/install_tools.sh
          oc version
          op --version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm install -g newman
      - name: run
        working-directory: ./auth-api/tests/postman
        run: |
          newman --version
          vaults='[{"vault": "relationship","application": ["auth-api"]}]'
          newman run auth-api.postman_collection.json -e auth-api.postman_environment.json `./get_globals.sh ${{ secrets.op_parameters }} -e "postman" -v "${vaults}"`
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*Auth API Postman test failed*"
          channel: "#relationship-developers"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: false
          token: ${{ secrets.GITHUB_TOKEN }}
