#Deploy to Test environment after the PR get merged
name: Auth API CD - deploy to Test

on:
  push:
    branches:
      - master
    paths:
      - "auth-api/**"

env:
  IMAGE_NAME: auth-api-gh
  TAG_NAME: test

jobs:
  auth-api-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry
        run: echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ secrets.OPENSHIFT_REGISTRY }} -u ${{ secrets.OPENSHIFT_SA_NAME}} --password-stdin
      - name: Pull base image
        working-directory: ./auth-api
        run: docker pull ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
      - name: Build image
        uses: vrutkovs/action-s2i@master
        with:
          path: ./auth-api
          base: ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
          image: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/${{env.IMAGE_NAME}}
      - name: Push image
        working-directory: ./auth-api
        run: |
          docker push ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/$IMAGE_NAME:$TAG_NAME
      - name: Install openshift cli
        working-directory: ./auth-api
        run: |
          sudo curl -sLo /tmp/oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          sudo tar xzvf /tmp/oc.tar.gz -C /tmp/
          sudo mv /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/local/bin/
          sudo rm -rf /tmp/oc.tar.gz /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
          sudo chmod +x /usr/local/bin/oc
          oc version
      - name: Login Openshift
        working-directory: ./auth-api
        run: |
          oc ${{ secrets.oc_parameters }}
          oc project ${{ secrets.OPENSHIFT_REPOSITORY_TEST }}
      - name: Install Jq and 1password cli
        working-directory: .
        run: |
          sudo apt install curl unzip jq --yes
          sudo curl -o 1password.zip https://cache.agilebits.com/dist/1P/op/pkg/v0.8.0/op_linux_amd64_v0.8.0.zip
          sudo unzip 1password.zip -d /usr/local/bin
          sudo rm 1password.zip
          sudo chmod +x /usr/local/bin/op
      - name: Set Deployment Environement Variables
        working-directory: .
        run: |
          op --version
          vaults='[{ "vault": "shared", "application": ["keycloak"]}, {"vault": "relationship","application": ["postgres-auth", "auth-api"]}]'
          ./setenv_secret.sh ${{ secrets.op_parameters }} -e "dev" -v "${vaults}" -a "${IMAGE_NAME}-${TAG_NAME}"
      - name: Rollout new deployment
        working-directory: ./auth-api
        run: |
          oc rollout latest dc/$IMAGE_NAME-TAG_NAME
          oc rollout status dc/$IMAGE_NAME-TAG_NAME -w
