name: Auth API CI

on:
  pull_request:
    paths:
      - "auth-api/**"
      - "build-deps/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./auth-api

jobs:
  auth-api-ci:
    uses: pwei1018/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "auth-api"
      working_directory: "./auth-api"
      codecov_flag: "authapi"
